[pytest]
addopts = -v -s --html=reports/report.html --self-contained-html --tracing=retain-on-failure
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Quick sanity tests for core functionality
    regression: Extensive regression suite
    ui: Frontend visual validations
    security: Vulnerability boundary tests
